apiVersion: v1
kind: Service
metadata:
  name: chaos-3-loadbalancer-{{ENVIRONMENT}}
spec:
  selector:
    app: chaos-3-{{ENVIRONMENT}}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
