"""
Contains column names for the file containing the data. 
"""


ID_CLIENT_COL = "ID_CLIENT"
ORIGINE_LEAD_COL = "ORIGINE_LEAD"
SOURCE_LEAD_COL = "SOURCE_LEAD"
NIVEAU_LEAD_COL = "NIVEAU_LEAD"
QUALITE_LEAD_COL = "QUALITE_LEAD"
CONTACT_PAR_MAIL_COL = "CONTACT_PAR_MAIL"
CONTACT_PAR_TELEPHONE_COL = "CONTACT_PAR_TELEPHONE"
STATUT_ACTUEL_COL = "STATUT_ACTUEL"
CONVERTI_COL = "CONVERTI"
NB_VISITES_COL = "NB_VISITES"
DUREE_SUR_SITEWEB_COL = "DUREE_SUR_SITEWEB"
NB_PAGES_VUES_PAR_VISITE_COL = "NB_PAGES_VUES_PAR_VISITE"
DERNIERE_ACTIVITE_COL = "DERNIERE_ACTIVITE"
DERNIERE_ACTIVITE_NOTABLE_COL = "DERNIERE_ACTIVITE_NOTABLE"
PAYS_COL = "PAYS"
VILLE_COL = "VILLE"
SPECIALISATION_COL = "SPECIALISATION"
TAGS_COL = "TAGS"
INDEX_ACTIVITE_COL = "INDEX_ACTIVITE"
INDEX_PROFIL_COL = "INDEX_PROFIL"
SCORE_ACTIVITE_COL = "SCORE_ACTIVITE"
SCORE_PROFIL_COL = "SCORE_PROFIL"
ANNONCE_VUE_COL = "ANNONCE_VUE"
MAGAZINE_COL = "MAGAZINE"
ARTICLE_JOURNAL_COL = "ARTICLE_JOURNAL"
FORUM_COL = "FORUM"
JOURNAUX_COL = "JOURNAUX"
PUB_DIGITALE_COL = "PUB_DIGITALE"
RECOMMANDATION_COL = "RECOMMANDATION"
COMMENT_ENTENDU_PARLER_COL = "Comment avez-vous entendu parler de nous ?"
SOUHAITE_RECEVOIR_INFOS_COL = "Souhaites-tu recevoir plus d'infos sur notre cours ?"
SOUHAITE_RECEVOIR_MAJ_COL = "Souhaites-tu recevoir des mises à jour sur nos programmes ?"
SOUHAITE_RECEVOIR_MSG_COL = "Souhaites-tu recevoir des mises à jour par message privé ?"
SOUHAITE_PAYER_CHEQUE_COL = "Souhaites-tu payer par chèque ?"
SOUHAITE_LIVRE_BLANC_COL = "Souhaites-tu recevoir une copie de notre livre blanc ?"

TARGET = CONVERTI_COL

FEATURES = [
    ID_CLIENT_COL,
    ORIGINE_LEAD_COL,
    SOURCE_LEAD_COL,
    NIVEAU_LEAD_COL,
    QUALITE_LEAD_COL,
    CONTACT_PAR_MAIL_COL,
    CONTACT_PAR_TELEPHONE_COL,
    STATUT_ACTUEL_COL,
    NB_VISITES_COL,
    DUREE_SUR_SITEWEB_COL,
    NB_PAGES_VUES_PAR_VISITE_COL,
    DERNIERE_ACTIVITE_COL,
    DERNIERE_ACTIVITE_NOTABLE_COL,
    PAYS_COL,
    VILLE_COL,
    SPECIALISATION_COL,
    TAGS_COL,
    INDEX_ACTIVITE_COL,
    INDEX_PROFIL_COL,
    SCORE_ACTIVITE_COL,
    SCORE_PROFIL_COL,
    ANNONCE_VUE_COL,
    MAGAZINE_COL,
    ARTICLE_JOURNAL_COL,
    FORUM_COL,
    JOURNAUX_COL,
    PUB_DIGITALE_COL,
    RECOMMANDATION_COL,
    COMMENT_ENTENDU_PARLER_COL,
    SOUHAITE_RECEVOIR_INFOS_COL,
    SOUHAITE_RECEVOIR_MAJ_COL,
    SOUHAITE_RECEVOIR_MSG_COL,
    SOUHAITE_PAYER_CHEQUE_COL,
    SOUHAITE_LIVRE_BLANC_COL,
]
